### ISSUE TITLE
Deadlock in the pre-ckpt phase when the checkpoint interval is short

### ISSUE THREAD

**Issue by JainTwinkle** [mpickpt/mana#161]
Quoting @marcpb94 from #133:

> It seems to be working now! I tried with mpi_hello_world with 1 rank and a heat distribution application (that we usually use for testing) with 4 ranks.

> However, there seems to be an issue we already noticed in the old version of MANA, and we were hoping it was fixed in the new version. It seems to happen with our heat distribution application, I attach the source code so that you are able to reproduce the problem. [heatdis.zip](https://github.com/mpickpt/mana/files/8797781/heatdis.zip)

> The issue is that when checkpointing with relatively short intervals(and letting it execute for a few minutes), the execution eventually encounters a deadlock in the pre-checkpoint phase. Specifically, at least one of the MPI processes gets stuck in the drainSendRecv() function in the DMTCP_EVENT_PRECHECKPOINT case from mpi_plugin_event_hook().

**Comment by JainTwinkle** [comment]
@marcpb94,

Could you provide the backtrace of the hanging process (all threads) and specific instructions to reproduce the issue? For example, the launch command, input to the executable, and short interval (2 sec?).

Thanks!

**Comment by gc00** [comment]
@JainTwinkle  @marcpb94  Does this dreadlock occur if you choose a longer checkpoint interval, such as 5 minutes?
This might be a long-known issue for short checkpoint intervals.  We were not concentrating on it earlier, when we were concentrating on making MANA more robust.
But now that MANA is becoming more robust, this might be a good time to analyze what is causing the dreadlock.

**Comment by JainTwinkle** [comment]
Thanks, @marcpb94! I was able to reproduce this issue. We are looking into it.

@karya0  @xuyao0127   @dahongli 
Rank 3 is the one that is currently stuck. Please find the backtrace of all four ranks here: [heat-distribution-4-ranks-backtrace.txt](https://github.com/mpickpt/mana/files/8808794/heat-distribution-4-ranks-backtrace.txt)

Yao,
We suspect that this might be an issue in the design while draining messages from `MPI_Isend`, and we think you would better know about the pre-ckpt phase algorithm. Could you please look at the backtraces?
The source is available here: [heatdis.zip](https://github.com/mpickpt/mana/files/8797781/heatdis.zip)

**Comment by JainTwinkle** [comment]
Update: @xuyao0127 says that he is able to reproduce the issue on Cori, and he is working on it.

**Comment by xuyao0127** [comment]
As @JainTwinkle said, this is a general bug in point-to-point communication. When draining point-to-point messages at checkpoint time, MPI_Iprobe detected an available message in the network, but the following MPI_Recv function can not receive the message and blocks the checkpoint progress. There is a similar heat equation program included in MANA that uses blocking point-to-point communication, but it doesn't have this issue. So I believe it's related to multiple non-blocking communications before the checkpoint.

I observed a pattern that between two neighboring ranks, one rank has created an MPI_Isend and an MPI_Irecv request, and wait on both requests. The other rank is at the beginning of this round of communication (no request created). Currently, I can not reproduce the same bug with 2 ranks or a simpler test program. I am still working on it.
