### ISSUE TITLE
Problem with MPI_STATUS_IGNORE in MPI_Sendrecv

### ISSUE THREAD

**Issue by Marc-Miranda** [mpickpt/mana#186]
Good morning,

I was trying to run MANA with LAMMPS and encountered a problem with the implemented wrapper for MPI_Sendrecv. LAMMPS uses MPI_STATUS_IGNORE, but then in the wrapper it tries to dereference it, and the application does not crash but does not continue either. 
Changing
```
*status = sts[1];
```
for 
```
if( status != MPI_STATUS_IGNORE ){
     *status = sts[1];
}
```
solved the issue. I submit a minimal reproducible code reproducing the bug. Have a nice day!
[main.c.gz](https://github.com/mpickpt/mana/files/9019635/main.c.gz)

**Comment by JainTwinkle** [comment]
Thanks, @Marc-Miranda. I have created a PR to include your suggested fix.

**Comment by Marc-Miranda** [comment]
Hello! Sorry for bringing this up again. It seems to me there is an error in the Sendrecv wrapper. Shouldn't
```
if (status != MPI_STATUS_IGNORE || status != FORTRAN_MPI_STATUS_IGNORE) {
    *status = sts[1];
}
```
be 
```
if (status != MPI_STATUS_IGNORE && status != FORTRAN_MPI_STATUS_IGNORE) {
    *status = sts[1];
}
```
as is done at every other wrapper?

Best,
Marc

**Comment by JainTwinkle** [comment]
@Marc-Miranda Thanks for catching. I will fix it today.

**Comment by JainTwinkle** [comment]
@Marc-Miranda It's merged now!
