### ISSUE TITLE
Wrapper for MPI_Type_hvector needed for iPic3D

### ISSUE THREAD

**Issue by Marc-Miranda** [mpickpt/mana#189]
Good afternoon,

I was trying to run [iPic3D](https://kth-hpc.github.io/iPIC3D/) with MANA, but iPic3D uses MPI_Type_hvector, for which there is no wrapper implemented. Could it be possibly be implemented? 

Thank you,
Marc

**Comment by chirag-singh-memverge** [comment]
Added
