### ISSUE TITLE
Problem with the MPI_Type_hvector wrapper for iPic3D

### ISSUE THREAD

**Issue by Marc-Miranda** [mpickpt/mana#195]
Good afternoon,
Some days ago I asked whether a wrapper for MPI_Type_hvector could be implemented, as iPic3D required it. @chirag-singh-memverge was kind enough to implement it. Thank you! However, the assumption that the stride must be a multiple of the size of the type does not hold for iPic3D. Is there an easy fix to this?

Thank you,
Marc

**Comment by chirag-singh-memverge** [comment]
This PR should have the fix: https://github.com/mpickpt/mana/pull/196

**Comment by chirag-singh-memverge** [comment]
@Marc-Miranda Please apply the PR + test to see if the issue is resolved so we can merge

**Comment by Marc-Miranda** [comment]
Hello!
Sorry for the delay. I did not have access to the computer during the last week. I have now checked it and it seems to work. Now I get a new error for a different implemented wrapper, but not this. I will open a new issue, so we can close this. Thank you both!

**Comment by JainTwinkle** [comment]
Thanks for the confirmation!
