### ISSUE TITLE
Implemented wrapper for MPI_Cart_create() not working with iPic3D

### ISSUE THREAD

**Issue by Marc-Miranda** [mpickpt/mana#203]
Good morning!
After @chirag-singh-memverge kindly solved the issue with the implemented wrapper for MPI_Type_hvector, a new problem arose. Now the program is complaining that the current implementation for the MPI_Cart_create() wrapper only supports one cartesian communicator. However, iPic3D creates more than one. Is there any easy solution? 
Thank you,
Marc

**Comment by JainTwinkle** [comment]
Hi Marc,

We have already fixed this issue in the newer commits. Kindly update your MANA's repository and test again. Let us know if the issue persists.

Best,
Twinkle

**Comment by Marc-Miranda** [comment]
Hello Twinkle,

Thank you! I was in the Type-refactoring branch and it was not fixed there, but after the merge now it works!

Best,
Marc

**Comment by JainTwinkle** [comment]
Thanks for confirming. I am closing this issue.
